services:
  laravel-echo-server:
    build: .
    container_name: laravel-echo-server
    restart: unless-stopped
    ports:
      - "${LARAVEL_ECHO_SERVER_PORT:-6001}:${LARAVEL_ECHO_SERVER_PORT:-6001}"
    environment:
      - LARAVEL_ECHO_SERVER_AUTH_HOST=${LARAVEL_ECHO_SERVER_AUTH_HOST:-http://localhost}
      - LARAVEL_ECHO_SERVER_AUTH_ENDPOINT=${LARAVEL_ECHO_SERVER_AUTH_ENDPOINT:-/socket/auth}
      - LARAVEL_ECHO_SERVER_HOST=${LARAVEL_ECHO_SERVER_HOST:-0.0.0.0}
      - LARAVEL_ECHO_SERVER_PORT=${LARAVEL_ECHO_SERVER_PORT:-6001}
      - LARAVEL_ECHO_SERVER_PROTOCOL=${LARAVEL_ECHO_SERVER_PROTOCOL:-http}
      - LARAVEL_ECHO_SERVER_DEV_MODE=${LARAVEL_ECHO_SERVER_DEV_MODE:-false}
      - LARAVEL_ECHO_SERVER_DATABASE=${LARAVEL_ECHO_SERVER_DATABASE:-redis}
      - LARAVEL_ECHO_SERVER_REDIS_HOST=redis
      - LARAVEL_ECHO_SERVER_REDIS_PORT=${LARAVEL_ECHO_SERVER_REDIS_PORT:-6379}
      - LARAVEL_ECHO_SERVER_REDIS_PASSWORD=${LARAVEL_ECHO_SERVER_REDIS_PASSWORD:-}
      - LARAVEL_ECHO_SERVER_REDIS_DB=${LARAVEL_ECHO_SERVER_REDIS_DB:-0}
      - LARAVEL_ECHO_SERVER_REDIS_KEY_PREFIX=${LARAVEL_ECHO_SERVER_REDIS_KEY_PREFIX:-}
      - LARAVEL_ECHO_SERVER_CORS_ORIGIN=${LARAVEL_ECHO_SERVER_CORS_ORIGIN:-*}
      - LARAVEL_ECHO_SERVER_CORS_METHODS=${LARAVEL_ECHO_SERVER_CORS_METHODS:-GET,POST}
      - LARAVEL_ECHO_SERVER_CORS_HEADERS=${LARAVEL_ECHO_SERVER_CORS_HEADERS:-Origin,Content-Type,X-Auth-Token,X-Requested-With,Accept,Authorization,X-CSRF-TOKEN,X-Socket-Id}
      - LARAVEL_ECHO_SERVER_CORS_CREDENTIALS=${LARAVEL_ECHO_SERVER_CORS_CREDENTIALS:-true}
      - LARAVEL_ECHO_SERVER_HTTP_SUBSCRIBER=${LARAVEL_ECHO_SERVER_HTTP_SUBSCRIBER:-false}
      - LARAVEL_ECHO_SERVER_REDIS_SUBSCRIBER=${LARAVEL_ECHO_SERVER_REDIS_SUBSCRIBER:-true}
      - LARAVEL_ECHO_SERVER_API_ALLOW_CORS=${LARAVEL_ECHO_SERVER_API_ALLOW_CORS:-true}
      - LARAVEL_ECHO_SERVER_API_ALLOW_ORIGIN=${LARAVEL_ECHO_SERVER_API_ALLOW_ORIGIN:-*}
      - LARAVEL_ECHO_SERVER_API_ALLOW_METHODS=${LARAVEL_ECHO_SERVER_API_ALLOW_METHODS:-GET, PUT, POST, DELETE, HEAD, OPTIONS}
      - LARAVEL_ECHO_SERVER_API_ALLOW_HEADERS=${LARAVEL_ECHO_SERVER_API_ALLOW_HEADERS:-Origin, Content-Type, X-Auth-Token, X-Requested-With, Accept, Authorization, X-CSRF-TOKEN, X-Socket-Id}
      - LARAVEL_ECHO_SERVER_ALLOW_PRIVATE_CHANNELS=${LARAVEL_ECHO_SERVER_ALLOW_PRIVATE_CHANNELS:-true}
    depends_on:
      - redis
    networks:
      - echo-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:' + (process.env.LARAVEL_ECHO_SERVER_PORT || 6001) + '/socket.io/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => { process.exit(1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: laravel-echo-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --appendonly yes ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - echo-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  echo-network:
    driver: bridge